### ISSUE TITLE
POSIX compliant FS storage doesn't work unless you manually chcon -R -t nfs_t mountpoint

### ISSUE THREAD

**Issue by ahadas** [oVirt/vdsm#204]
Background details:
https://lists.ovirt.org/archives/list/users@ovirt.org/thread/TBRERXNEEUYEFW2FAZUWVLF5TFODFGKM/

I was not able to create posix storage through the UI.  It
fails with a strange error:

Error while executing action AddPosixFsStorageDomain: Unexpected exception

Eventually I tracked down the real error to sanlock:

2022-02-04 13:15:27 16723 [826]: open error -13 EACCES: no permission to open   
/rhev/data-center/mnt/_dev_sdb1/13a731d2-e1d2-4998-9b02-ac46899e3159/dom_md/ids 
2022-02-04 13:15:27 16723 [826]: check that daemon user sanlock 179 group
sanlock 179 has access to disk or file.

This was resolved by doing:

sudo chcon -R -t nfs_t /mountpoint

Version-Release number of selected component (if applicable):

ovirt 4.4.10.6-1.el8 running on RHEL 8.5

How reproducible:

100%

Steps to Reproduce:

See this email for detailed steps:
https://lists.ovirt.org/archives/list/users@ovirt.org/message/CSKCHQVWWD7EW3A4HPA37RJTKACFATO6/

Original bug: https://bugzilla.redhat.com/2050721

**Comment by nirs** [comment]
Daniel reply can help to find the right fix:
https://bugzilla.redhat.com/2050721#c2

The fix is likey not in oVirt, but in the selinux security policy.

**Comment by aesteve-rh** [comment]
Yes, thanks. I saw the comment. Indeed, that points us towards an action to take from vdsm.

**Comment by aesteve-rh** [comment]
`restorecon` also changes the label, but to `mnt_t` which seems to be the correct label (I see the same label used for other domains).

```
Relabeled /rhev/data-center/mnt/_dev_sda/ab531e14-d153-42f9-acc2-2d67ece7c3cb/dom_md from system_u:object_r:unlabeled_t:s0 to system_u:object_r:mnt_t:s0
```

Maybe calling `restorecon` after mounting might be a good workaround until a fix comes from selinux?

**Comment by nirs** [comment]
So restorecon fixes the issue?

**Comment by aesteve-rh** [comment]
I tried with a manually mounted device, not with vdsm. But the label is changed into a valid one in my tests with `restorecon`, so it looks promising. I can implement it to try and verify that the issue is fixed and the SD can be added from the engine.

**Comment by nirs** [comment]
The question is not if the label changed, but if you could reproduce the issue (sanlock fails
to access files in the mount), and after running restorecon the issue is solved.

Solved also mean that system works after deactivating and activating the storage domain
and the host.

If this works check if this can be done of the local directory mounted by vdsm, so a user
can fix the labels once before using the storage.

I don't think vdsm should change selinux labels, user should use properly labeled file
system.

Note also that mounting a local directory on a host as shared storage is not supported and
will break when you add another host to the setup. We should not try to make unsupported
configuration work.

**Comment by aesteve-rh** [comment]
If I try to reproduce the issue by just creating the SD from scratch (the host has an FC device that is blacklisted from multipath and I create a POSIX compliant FS pointing to its path) I get a permission error:
```
2022-06-08 13:14:35,624+0200 INFO  (jsonrpc/2) [storage.mount] mounting /dev/sda at /rhev/data-center/mnt/_dev_sda (mount:207)
2022-06-08 13:14:35,678+0200 INFO  (jsonrpc/2) [IOProcessClient] (Global) Starting client (__init__:340)
2022-06-08 13:14:35,695+0200 INFO  (ioprocess/305796) [IOProcess] (Global) Starting ioprocess (__init__:465)
2022-06-08 13:14:35,698+0200 WARN  (jsonrpc/2) [storage.oop] Permission denied for directory: /rhev/data-center/mnt/_dev_sda with permissions:7 (outOfProcess:194)
2022-06-08 13:14:35,698+0200 INFO  (jsonrpc/2) [storage.mount] unmounting /rhev/data-center/mnt/_dev_sda (mount:215)
2022-06-08 13:14:35,747+0200 ERROR (jsonrpc/2) [storage.storageServer] Could not connect to storage server (storageServer:92)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vdsm/storage/fileSD.py", line 82, in validateDirAccess
    getProcPool().fileUtils.validateAccess(dirPath)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/outOfProcess.py", line 195, in validateAccess
    raise OSError(errno.EACCES, os.strerror(errno.EACCES))
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vdsm/storage/storageServer.py", line 90, in connect_all
    con.connect()
  File "/usr/lib/python3.6/site-packages/vdsm/storage/storageServer.py", line 258, in connect
    six.reraise(t, v, tb)
  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/vdsm/storage/storageServer.py", line 251, in connect
    self.getMountObj().getRecord().fs_file)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/fileSD.py", line 93, in validateDirAccess
    raise se.StorageServerAccessPermissionError(dirPath)
vdsm.storage.exception.StorageServerAccessPermissionError: Permission settings on the specified path do not allow access to the storage. Verify permission settings on the specified storage path.: 'path = /rhev/data-center/mnt/_dev_sda'
```

To really reproduce the error I need to manually mount the fs in the expected path `/rhev/data-center/mnt/_dev_sda` and chown the folder to vdsm. Then I get the sanlock error as described in the bug.

Then `restorecon` changes the sanlock label, but if I try to create the SD again to see if it fixes the issue I get a different error:

```
2022-06-08 13:09:23,295+0200 INFO  (jsonrpc/6) [vdsm.api] FINISH createStorageDomain error=Storage domain is not empty - requires cleaning: ('/dev/sda',) from=::ffff:192.168.122.96,47294, flow_id=430e99a9, task_id=a50e7d05-dab6-4ebb-96af-c4e528f83805 (api:52)
2022-06-08 13:09:23,295+0200 ERROR (jsonrpc/6) [storage.taskmanager.task] (Task='a50e7d05-dab6-4ebb-96af-c4e528f83805') Unexpected error (task:877)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vdsm/storage/task.py", line 884, in _run
    return fn(*args, **kargs)
  File "</usr/lib/python3.6/site-packages/decorator.py:decorator-gen-123>", line 2, in createStorageDomain
  File "/usr/lib/python3.6/site-packages/vdsm/common/api.py", line 50, in method
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/hsm.py", line 2340, in createStorageDomain
    max_hosts=max_hosts)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/nfsSD.py", line 95, in create
    version)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/nfsSD.py", line 60, in _preCreateValidation
    raise se.StorageDomainNotEmpty(typeSpecificArg)
vdsm.storage.exception.StorageDomainNotEmpty: Storage domain is not empty - requires cleaning: ('/dev/sda',)
```

I feel I am doing something fundamentally wrong in how I am trying to reproduce the issue, but not sure what.
