### ISSUE TITLE
mom issue

### ISSUE THREAD

**Issue by piramix** [oVirt/vdsm#345]
After upgrading 4.4 to 4.5.3 I'm getting mom-vdsm service issues

2022-10-23 16:37:35,681 - mom.Policy - INFO - Loaded policy '00-defines'
2022-10-23 16:37:35,682 - mom - ERROR - Failed to initialize MOM threads
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mom/__init__.py", line 35, in run
    host_monitor, guest_manager)
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 42, in __init__
    self.load_policy()
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 71, in load_policy
    read_policy(fname, name.split('.policy')[0])
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 53, in read_policy
    return self.policy.set_policy(policy_name, policyStr)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Policy.py", line 64, in set_policy
    self.code = get_code(Evaluator(), self._cat_policies())
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 543, in get_code
    tokens = scanner.tokenize(string)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 72, in tokenize
    GenericScanner.tokenize(self, input)
  File "/usr/lib/python3.6/site-packages/mom/Policy/spark.py", line 78, in tokenize
    add_lines = self.index2func[i](groups[i], line)
TypeError: t_default() takes 2 positional arguments but 3 were given

**Comment by mz-pdm** [comment]
This has already been fixed in https://github.com/oVirt/mom/pull/17.
