### ISSUE TITLE
Ovirt 4.3 VDSM MoM is failing to start 

### ISSUE THREAD

**Issue by volga629-1** [oVirt/vdsm#421]
Hello Everyone, 

Ovirt 4.3 Host is Unresponsive mode where mom service is not coming up . I see in log traceback 
Any  hint thank you.

```
2024-07-05 20:47:40,991 - mom - ERROR - Failed to initialize MOM threads
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mom/__init__.py", line 29, in run
    hypervisor_iface = self.get_hypervisor_interface()
  File "/usr/lib/python2.7/site-packages/mom/__init__.py", line 217, in get_hypervisor_interface
    return module.instance(self.config)
  File "/usr/lib/python2.7/site-packages/mom/HypervisorInterfaces/vdsmjsonrpcclientInterface.py", line 96, in instance
    return JsonRpcVdsmClientInterface()
  File "/usr/lib/python2.7/site-packages/mom/HypervisorInterfaces/vdsmjsonrpcclientInterface.py", line 31, in __init__
    self._vdsm_api = client.connect(host="localhost")
  File "/usr/lib/python2.7/site-packages/vdsm/client.py", line 157, in connect
    raise ConnectionError(host, port, use_tls, timeout, e)
ConnectionError: Connection to localhost:54321 with use_tls=True, timeout=60 failed: [Errno 13] Permission denied

```

**Comment by sandrobonazzola** [comment]
oVirt 4.3 reached EOL long time ago, please upgrade to 4.5
